<?php
// module/Album/view/album/album/index.phtml:

$title = 'My cars';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('cars', array('action'=>'add'));?>">Add new car</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($carss as $cars) : ?>
<tr>
    <td><?php echo $this->escapeHtml($cars->title);?></td>
    <td><?php echo $this->escapeHtml($cars->artist);?></td>
    <td>
        <a href="<?php echo $this->url('cars',
            array('action'=>'edit', 'id' => $cars->id));?>">Edit</a>
        <a href="<?php echo $this->url('cars',
            array('action'=>'delete', 'id' => $cars->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>